### PR TITLE
Toychain extraction

### PR DESCRIPTION
**Pull request by dranov**
There is still one pending issue with the NetAddr representation, which I have not yet had time to fix.

### CODE REVIEW

**Comment by dranov** [comment]
@palmskog Coq 8.9 is now a hard dependency (we rely on `HexStrings` from the standard library). Would it be possible to create a Docker image with Coq 8.9 for the Travis build?

**Comment by dranov** [comment]
@palmskog I am having some trouble getting the Travis build to work. There are two separate issues (more might pop up later):

1. One of the proofs in `TypesImpl.v` [fails](https://travis-ci.org/certichain/toychain/jobs/526180573#L569) on the Travis build, but works on two of my machines (Ubuntu 18.04 and WSL/Ubuntu 16.04). Could you check whether [this commit](https://github.com/certichain/toychain/pull/22/commits/f80890d5b1520c04e39fe2c77294486884a58b51) builds on your machine?

2. For the extraction, some extra dependencies are introduced (see [this diff](https://github.com/certichain/toychain/pull/22/commits/ebd589f954a30707d71a3076b837242bf95d57bd)). Pulling these [fails](https://travis-ci.org/certichain/toychain/jobs/526187972#L445) on the Travis build, I think because some system libraries might be missing.

I'd really appreciate some help with these.

**Comment by palmskog** [comment]
@dranov the Travis build uses MathComp version 1.8.0.

Here's one way to make the failing proof in `TypesImpl.v` pass in 1.8.0:
```coq
Lemma eq_NP : Equality.axiom N.eqb.
Proof.
case=>[x|p x]//=; case: x.
by constructor 1; apply N.Private_Tac.eq_refl.
by constructor 2.
by constructor 2.
move=> p' /=; case X: (BinPos.Pos.eqb p p'); constructor.
  by move/BinPos.Peqb_true_eq: X =>->.
by move/BinPos.Pos.eqb_neq: X => X; case.
Qed.
```

**Comment by palmskog** [comment]
As for the build issue, there's no way to fix that without building a completely new Docker image, which I don't have cycles to do at the moment.

I would suggest that you separate out the "pure Coq build" into one OPAM package and the "extracted build" into another separate OPAM package definition, and only run the former in Travis. Here is one project where I do precisely that: https://github.com/coq-community/chapar

**Comment by palmskog** [comment]
@dranov to make it easier for me to fix some things about the build as they arise by making my own commits, I think you should merge this PR into the `extraction` branch of this repo for now, and there can be a different PR later for merging into `master`.

**Comment by dranov** [comment]
@palmskog That sounds reasonable. Done, and thank you!

**Pull request merged**
