### PR TITLE
Port to FCSL PCM library

### PR DESCRIPTION
**Pull request by palmskog**
IMDEA released an updated (OPAM) version of their [FCSL PCM library](https://github.com/imdea-software/fcsl-pcm), replacing the old HTT development. Here is my port to that library, which will obviate/distribute some of the maintenance burden. As before, let me know if you have any concerns, otherwise I will merge this in the near future.

### CODE REVIEW

**Comment by ilyasergey** [comment]
Wow, that was quick (the announcement by Anton in Coq-Club was just yesterday!). 

Looks good to me and compiles without problems. Approved.

**Comment by anton-trunov** [comment]
Hi folks! That was indeed quick! Thanks for integrating `coq-fcsl-pcm`. 

Now that this branch has been merged we can discuss if you would like us to put this library into our continuous integration system ([here](https://github.com/imdea-software/fcsl-pcm/issues/2) is where we started the conversation).

Btw, I manually checked that your latest master compiles against our latest master of the future (larger) `coq-fcsl` package  (it's in our private repo, but we will open-source it later this year).

**Comment by ilyasergey** [comment]
@anton-trunov sure, feel free to add this to you CI. We will probably also migrate pnp (https://github.com/ilyasergey/pnp) and Disel (https://github.com/DistributedComponents/disel) to this as well some time soon, so it would be good to keep them in sync.

**Comment by anton-trunov** [comment]
@ilyasergey Good to know. Happy hacking!

**Comment by ilyasergey** [comment]
Any plans to make HTT a standalone opam package, dependent on the PCM one?

**Comment by anton-trunov** [comment]
Oh, yes. The plan was to release the full FCSL library which includes the PCM subpart. Together with deprecating the `coq-fcsl-pcm` package. Initially, we didn't plan to release `coq-fcsl-pcm` as a standalone package.

But let's see how it goes and maybe we will be able to separate those. So I'd appreciate your feedback on this matter.

**Pull request merged**
