### PR TITLE
Metadata for Travis

### PR DESCRIPTION
**Pull request by palmskog**
Here are metadata files for enabling Travis CI for this repository. This allows continuous checking that changes do not break proofs.

@dranov Is there any chance you could enable Travis by connecting your Github account to [Travis CI](https://travis-ci.org) and then selecting the appropriate button on your Travis profile? See [here](https://docs.travis-ci.com/user/getting-started/) for some more information.

(I currently don't have access rights to enable Travis for this repository, but I tested that the metadata works in my fork.)

### CODE REVIEW

**Comment by dranov** [comment]
Sure. I can't do it right now (on mobile), but I'll look into it tomorrow ASAP.

**Comment by palmskog** [comment]
Great, feel free to merge this pull request once you have enabled Travis. It should then be obvious whether it worked (spawned a Travis job) or not.

**Comment by dranov** [comment]
It seems I can't fully set it up myself, either. Only @ilyasergey (as owner of the certichain GitHub organisation) can approve the permission request from Travis. Once he does, we should be good to go.

**Comment by ilyasergey** [comment]
@dranov @palmskog Okay, I granted the permission. Feel free to proceed with merging the PR.

**Comment by palmskog** [comment]
@dranov I merged the commit but it didn't trigger any build. Could you check https://travis-ci.org/profile/certichain and see if you can press the button to activate the toychain repo?

**Comment by ilyasergey** [comment]
@palmskog done

**Comment by palmskog** [comment]
Thanks @ilyasergey now it works.

**Pull request merged**
